spring:
  application:
    name: CareerCoachBook
  profiles:
    active: local
  datasource:
    driver-class-name: ${booking.datasource.driver-class-name}
    url: jdbc:mysql://${booking.datasource.host}:${booking.datasource.port}/${booking.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${booking.datasource.username}
    password: ${booking.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fang.careercoachbook.entity
  configuration:
    map-underscore-to-camel-case: true